### ISSUE TITLE
Resizing volumes 

### ISSUE THREAD

**Issue by evertonaulian** [zadarastorage/zadara-csi#1]
When we create a Persistent Volume Claim with a specific size and then update that file with a new size for the volume, the csi is adding this new size to the volume created instead of resizing the disk to the value described in the yaml file.

For example, if we define a Persistent Volume Claim with 100GiB
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zadara-zadara-nas-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-zadara-zadara-nas`

![image](https://user-images.githubusercontent.com/38323221/76361765-70afb500-62fe-11ea-8748-27c9633935ef.png)

And then resize it to 150GiB
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zadara-zadara-nas-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 150Gi
  storageClassName: csi-zadara-zadara-nas`

![image](https://user-images.githubusercontent.com/38323221/76361743-668db680-62fe-11ea-8ab9-14fa259763c2.png)

The VPSA is resizing the disk to 250GiB, instead of 150GiB

**Comment by Levp-zadara** [comment]
Thank you for opening the issue, and such a detailed description!
Sorry it took this long to respond, just now have noticed I was not receiving any notifications from this repo.

The problem has already been fixed, and waiting for release. The fix will be available in 1.2.1+ version.

**Comment by Levp-zadara** [comment]
fixed in 1.2.6
